sonar.projectKey=Team-Sellora_sellora-order
sonar.organization=team-sellora
sonar.projectName=sellora-order
sonar.sources=src/Sellora.Order.Api,src/Sellora.Order.Domain,src/Sellora.Order.Infrastructure
sonar.tests=src/Sellora.Order.UnitTests,src/Sellora.Order.IntegrationTests
sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
sonar.exclusions=**/Migrations/**,**/obj/**,**/bin/**
