// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sellora.OrderService.Infrastructure.Persistence;

#nullable disable

namespace Sellora.OrderService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    [Migration("20260924075745_AddCheckInAndPayment")]
    partial class AddCheckInAndPayment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sellora.OrderService.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTimeOffset?>("CheckedOutAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checked_out_at");

                    b.Property<double?>("CheckoutLatitude")
                        .HasColumnType("double precision")
                        .HasColumnName("checkout_latitude");

                    b.Property<double?>("CheckoutLongitude")
                        .HasColumnType("double precision")
                        .HasColumnName("checkout_longitude");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("FulfilmentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("fulfilment_type");

                    b.Property<Guid>("InventoryOwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_owner_id");

                    b.Property<DateTimeOffset>("OrderDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("order_date");

                    b.Property<string>("OrderReference")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("order_reference");

                    b.Property<Guid>("ProvinceId")
                        .HasColumnType("uuid")
                        .HasColumnName("province_id");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_id");

                    b.Property<Guid>("SalesRepId")
                        .HasColumnType("uuid")
                        .HasColumnName("sales_rep_id");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("shop_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("subtotal");

                    b.Property<Guid>("TerritoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("territory_id");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total");

                    b.HasKey("OrderId")
                        .HasName("pk_customer_order");

                    b.HasIndex("ReservationId")
                        .HasDatabaseName("ix_customer_order_reservation");

                    b.HasIndex("CompanyId", "OrderReference")
                        .IsUnique()
                        .HasDatabaseName("uq_customer_order_company_reference");

                    b.HasIndex("CompanyId", "AgencyId", "OrderDate")
                        .HasDatabaseName("ix_customer_order_company_agency_date");

                    b.HasIndex("CompanyId", "ProvinceId", "OrderDate")
                        .HasDatabaseName("ix_customer_order_company_province_date");

                    b.HasIndex("CompanyId", "SalesRepId", "OrderDate")
                        .HasDatabaseName("ix_customer_order_company_rep_date");

                    b.HasIndex("CompanyId", "ShopId", "OrderDate")
                        .HasDatabaseName("ix_customer_order_company_shop_date");

                    b.HasIndex("CompanyId", "ShopId", "Status")
                        .HasDatabaseName("ix_customer_order_company_shop_status");

                    b.ToTable("customer_order", null, t =>
                        {
                            t.HasCheckConstraint("ck_customer_order_subtotal_non_negative", "subtotal >= 0");

                            t.HasCheckConstraint("ck_customer_order_total_non_negative", "total >= 0");
                        });
                });

            modelBuilder.Entity("Sellora.OrderService.Domain.Entities.OrderCheckIn", b =>
                {
                    b.Property<Guid>("OrderCheckInId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_check_in_id");

                    b.Property<bool>("Accepted")
                        .HasColumnType("boolean")
                        .HasColumnName("accepted");

                    b.Property<double?>("AccuracyMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("accuracy_meters");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<double>("DistanceMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("distance_meters");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<double>("RadiusMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("radius_meters");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("SalesRepId")
                        .HasColumnType("uuid")
                        .HasColumnName("sales_rep_id");

                    b.Property<double>("ShopLatitude")
                        .HasColumnType("double precision")
                        .HasColumnName("shop_latitude");

                    b.Property<double>("ShopLongitude")
                        .HasColumnType("double precision")
                        .HasColumnName("shop_longitude");

                    b.HasKey("OrderCheckInId")
                        .HasName("pk_order_check_in");

                    b.HasIndex("OrderId", "SalesRepId", "RecordedAt")
                        .HasDatabaseName("ix_order_check_in_order_rep_recorded");

                    b.ToTable("order_check_in", null, t =>
                        {
                            t.HasCheckConstraint("ck_order_check_in_distance", "distance_meters >= 0");

                            t.HasCheckConstraint("ck_order_check_in_latitude", "latitude BETWEEN -90 AND 90");

                            t.HasCheckConstraint("ck_order_check_in_longitude", "longitude BETWEEN -180 AND 180");
                        });
                });

            modelBuilder.Entity("Sellora.OrderService.Domain.Entities.OrderLine", b =>
                {
                    b.Property<Guid>("OrderLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_line_id");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("line_total");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product_name_snapshot");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPriceSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price_snapshot");

                    b.HasKey("OrderLineId")
                        .HasName("pk_order_line");

                    b.HasIndex("OrderId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("uq_order_line_order_product");

                    b.ToTable("order_line", null, t =>
                        {
                            t.HasCheckConstraint("ck_order_line_quantity_positive", "quantity > 0");

                            t.HasCheckConstraint("ck_order_line_unit_price_non_negative", "unit_price_snapshot >= 0");
                        });
                });

            modelBuilder.Entity("Sellora.OrderService.Domain.Entities.OrderVerificationStep", b =>
                {
                    b.Property<Guid>("OrderVerificationStepId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_verification_step_id");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("detail");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean")
                        .HasColumnName("passed");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("step");

                    b.HasKey("OrderVerificationStepId")
                        .HasName("pk_order_verification_step");

                    b.HasIndex("OrderId", "Step")
                        .IsUnique()
                        .HasDatabaseName("uq_order_verification_step_order_step");

                    b.ToTable("order_verification_step", (string)null);
                });

            modelBuilder.Entity("Sellora.OrderService.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("CheckInId")
                        .HasColumnType("uuid")
                        .HasColumnName("check_in_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<double>("DistanceMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("distance_meters");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("method");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("SalesRepId")
                        .HasColumnType("uuid")
                        .HasColumnName("sales_rep_id");

                    b.HasKey("PaymentId")
                        .HasName("pk_payment");

                    b.HasIndex("CheckInId");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("uq_payment_order");

                    b.ToTable("payment", null, t =>
                        {
                            t.HasCheckConstraint("ck_payment_amount_non_negative", "amount >= 0");
                        });
                });

            modelBuilder.Entity("Sellora.OrderService.Domain.Entities.OrderCheckIn", b =>
                {
                    b.HasOne("Sellora.OrderService.Domain.Entities.Order", null)
                        .WithMany("CheckIns")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_order_check_in_customer_order");
                });

            modelBuilder.Entity("Sellora.OrderService.Domain.Entities.OrderLine", b =>
                {
                    b.HasOne("Sellora.OrderService.Domain.Entities.Order", null)
                        .WithMany("Lines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_order_line_customer_order");
                });

            modelBuilder.Entity("Sellora.OrderService.Domain.Entities.OrderVerificationStep", b =>
                {
                    b.HasOne("Sellora.OrderService.Domain.Entities.Order", null)
                        .WithMany("VerificationSteps")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_order_verification_step_customer_order");
                });

            modelBuilder.Entity("Sellora.OrderService.Domain.Entities.Payment", b =>
                {
                    b.HasOne("Sellora.OrderService.Domain.Entities.OrderCheckIn", null)
                        .WithMany()
                        .HasForeignKey("CheckInId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payment_order_check_in");

                    b.HasOne("Sellora.OrderService.Domain.Entities.Order", null)
                        .WithOne("Payment")
                        .HasForeignKey("Sellora.OrderService.Domain.Entities.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payment_customer_order");
                });

            modelBuilder.Entity("Sellora.OrderService.Domain.Entities.Order", b =>
                {
                    b.Navigation("CheckIns");

                    b.Navigation("Lines");

                    b.Navigation("Payment");

                    b.Navigation("VerificationSteps");
                });
#pragma warning restore 612, 618
        }
    }
}
