// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sellora.OrderService.Infrastructure.Persistence;

#nullable disable

namespace Sellora.OrderService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    partial class OrderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sellora.OrderService.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("OrderDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("order_date");

                    b.Property<string>("OrderReference")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("order_reference");

                    b.Property<Guid>("ProvinceId")
                        .HasColumnType("uuid")
                        .HasColumnName("province_id");

                    b.Property<Guid>("SalesRepId")
                        .HasColumnType("uuid")
                        .HasColumnName("sales_rep_id");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("shop_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("subtotal");

                    b.Property<Guid>("TerritoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("territory_id");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total");

                    b.HasKey("OrderId")
                        .HasName("pk_customer_order");

                    b.HasIndex("CompanyId", "OrderReference")
                        .IsUnique()
                        .HasDatabaseName("uq_customer_order_company_reference");

                    b.HasIndex("CompanyId", "AgencyId", "OrderDate")
                        .HasDatabaseName("ix_customer_order_company_agency_date");

                    b.HasIndex("CompanyId", "ProvinceId", "OrderDate")
                        .HasDatabaseName("ix_customer_order_company_province_date");

                    b.HasIndex("CompanyId", "SalesRepId", "OrderDate")
                        .HasDatabaseName("ix_customer_order_company_rep_date");

                    b.HasIndex("CompanyId", "ShopId", "OrderDate")
                        .HasDatabaseName("ix_customer_order_company_shop_date");

                    b.ToTable("customer_order", null, t =>
                        {
                            t.HasCheckConstraint("ck_customer_order_subtotal_non_negative", "subtotal >= 0");

                            t.HasCheckConstraint("ck_customer_order_total_non_negative", "total >= 0");
                        });
                });

            modelBuilder.Entity("Sellora.OrderService.Domain.Entities.OrderLine", b =>
                {
                    b.Property<Guid>("OrderLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_line_id");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("line_total");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product_name_snapshot");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPriceSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price_snapshot");

                    b.HasKey("OrderLineId")
                        .HasName("pk_order_line");

                    b.HasIndex("OrderId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("uq_order_line_order_product");

                    b.ToTable("order_line", null, t =>
                        {
                            t.HasCheckConstraint("ck_order_line_quantity_positive", "quantity > 0");

                            t.HasCheckConstraint("ck_order_line_unit_price_non_negative", "unit_price_snapshot >= 0");
                        });
                });

            modelBuilder.Entity("Sellora.OrderService.Domain.Entities.OrderLine", b =>
                {
                    b.HasOne("Sellora.OrderService.Domain.Entities.Order", null)
                        .WithMany("Lines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_order_line_customer_order");
                });

            modelBuilder.Entity("Sellora.OrderService.Domain.Entities.Order", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
